	
#define ST_OP_CREATE_ACCOUNT			10007
#define ST_OP_SET_STATUS_PAYINFO		10008
#define ST_SKY_PURCHASE_BUNDLE_CHANGE_BDOM	10010

#define SKY_FLD_CUSTOMER_ID		PIN_MAKE_FLD(PIN_FLDT_STR, 10007)		
#define SKY_FLD_PROFILE_INFO		PIN_MAKE_FLD(PIN_FLDT_SUBSTRUCT, 10008)		
